apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datafrom-find-by-regex
  namespace: eso-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: $provider-secret-store

  target:
    name: datafrom-find-by-regex
    creationPolicy: Owner

  dataFrom:
  - find:
      name:
        regexp: "^secret-"
