apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: data-by-name
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store

  target:
    name: data-by-name
    creationPolicy: Owner

  data:
    - secretKey: secret-value
      remoteRef:
        key: secret-one
        property: "the-key"

