apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store

  target:
    name: synced-secret
    creationPolicy: Owner

  # data:
  #   - secretKey: dev-secret-test
  #     remoteRef:
  #       metadataPolicy: Fetch
  #       key: source-secret
  #       property: "labels"


  # data:
  # - secretKey: dev-secret-test
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: my-secret-parameter
  #     property: provider

  dataFrom:
  - extract:
      metadataPolicy: Fetch
      key: source-secret
      property: labels

  # dataFrom:
  # - find:
  #     name:
  #       regexp: "^example"

  # dataFrom:
  # - find:
  #     tags:
  #       author: seb
  #       environment: dev

  # dataFrom:
  # - find:
  #     name:
  #       regexp: "^example"
  # - find:
  #     tags:
  #       author: seb
  #       environment: dev
