apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-secret-store
spec:
  provider:
    azurekv:
      tenantId: "$TENANT_ID"
      vaultUrl: "$VAULT_URL"
      authSecretRef:
        clientId:
          name: azure-credentials
          key: clientid
          namespace: cred
        clientSecret:
          name: azure-credentials
          key: clientsecret
          namespace: cred