apiVersion: generators.external-secrets.io/v1alpha1
kind: Fake
metadata:
  name: fake-key
  namespace: eso-demo
spec:
  data:
    foo: bar
    baz: bang
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake
  namespace: eso-demo
spec:
  refreshInterval: 15s
  target:
    name: fake
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Fake
        name: fake-key