apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: awssm-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: "$AWS_REGION"
      auth:
        secretRef:
          accessKeyIDSecretRef: 
            name: aws-credentials 
            key: access-key  
            namespace: cred
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret
            namespace: cred
