apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1   
      auth:
        secretRef:
          accessKeyIDSecretRef: 
            name: aws-credentials 
            key: access-key  
            namespace: cred
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret
            namespace: cred
