apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      # Uncomment when running ESO locally and port-forwarding Vault
      # server: "http://127.0.0.1:8200"
      server: "http://vault.vault:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: cred
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: cred
data:
  token: cm9vdA==