# Apply this if you don't use Terraform
apiVersion: v1
kind: Namespace
metadata:
  name: remote
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-remote-sa
  namespace: remote
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: remote
  name: eso-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-remote-rb
  namespace: remote
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-secret-reader
subjects:
- kind: ServiceAccount
  name: my-remote-sa
  namespace: remote
