apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: remote-cluster
      server:
        url: "https://$CLUSTER_IP:8443" # this is "minikube ip"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: eso-demo
          key: ca.crt
      auth:
        serviceAccount:
          name: my-remote-sa
          namespace: eso-demo
