apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-secret-store
  namespace: eso-demo
spec:
  provider:
    kubernetes:
      remoteNamespace: remote
      server:
        url: "https://$CLUSTER_IP:8443" # this is "minikube ip"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: my-remote-sa
